# æœºåœºè®¢é˜…
proxy-providers:
  AirPort:
    url: "æœºåœºè®¢é˜…"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: DIRECT

# å…¨å±€é…ç½® 
port: 8080
socks-port: 1080
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
profile:
  store-selected: true
  store-fake-ip: true

# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "rule-set:private_domain,cn_domain"
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.apple.com"
    - "+.push.apple.com"
    - "+.wechat.com"
    - "+.wechatapp.com"
    - "+.qq.com"
    - "+.qpic.cn"
    - "+.vivox.com"
    - "+.msftncsi.com"
    - "+.msftconnecttest.com"

# å…¥ç«™  
tun:
  enable: true
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false

# DNSæ¨¡å—
dns:
  enable: true
  cache-algorithm: arc
  listen: 127.0.0.1:1053
  ipv6: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.lan"
    - "+.local"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  direct-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
 
# å‡ºç«™
pr: &pr {type: select, proxies: [âœ… Static, ğŸ‡­ğŸ‡° Hong Kong, ğŸ‡¹ğŸ‡¼ Tai Wan, ğŸ‡¸ğŸ‡¬ Singapore, ğŸ‡¯ğŸ‡µ Japan, ğŸ‡°ğŸ‡· Korea, ğŸ‡ºğŸ‡² United States, ğŸ¯ Proxy, DIRECT]}
proxy-groups:
  - {name: âœ… Static, type: select, proxies: [ğŸš€ Speed Test, ğŸ‡­ğŸ‡° Hong Kong, ğŸ‡¹ğŸ‡¼ Tai Wan, ğŸ‡¸ğŸ‡¬ Singapore, ğŸ‡¯ğŸ‡µ Japan, ğŸ‡°ğŸ‡· Korea, ğŸ‡ºğŸ‡² United States, ğŸ¯ Proxy, DIRECT]}
  - {name: ğŸš€ Speed Test, type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 300, tolerance: 20, filter: "(?=.*(æ¸¯|HK|(?i)Hong))|(?=.*(å°|TW|(?i)Tai))|(?=.*(æ–°|SG|(?i)Singapore))|(?=.*(æ—¥|JP|(?i)Japan))|(?=.*(éŸ©|KR|(?i)Korea))|(?=.*(ç¾|US|(?i)States|America))"}
  - {name: ğŸ¯ Proxy, type: select, include-all: true}
  - {name: ğŸ¤– AI, <<: *pr}
  - {name: ğŸ‘¨â€ğŸ’» GitHub, <<: *pr}
  - {name: ğŸ“¹ YouTube, <<: *pr}
  - {name: ğŸ¥ Netflix, <<: *pr}
  - {name: ğŸ¶ Spotify, <<: *pr}
  - {name: ğŸ® Game, <<: *pr}
  - {name: ğŸ“¢ Google, <<: *pr}
  - {name: ğŸªŸ Microsoft, <<: *pr}
  - {name: ğŸ Apple, <<: *pr}
  - {name: ğŸŸ Final, type: select, proxies: [âœ… Static, ğŸ¯ Proxy, DIRECT]}
  - {name: ğŸ‡­ğŸ‡° Hong Kong, type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 300, tolerance: 20, filter: "(?=.*(æ¸¯|HK|(?i)Hong))"}
  - {name: ğŸ‡¹ğŸ‡¼ Tai Wan, type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 300, tolerance: 20, filter: "(?=.*(å°|TW|(?i)Tai))"}
  - {name: ğŸ‡¸ğŸ‡¬ Singapore, type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 300, tolerance: 20, filter: "(?=.*(æ–°|SG|(?i)ğŸ‡¸ğŸ‡¬ Singapore))"}
  - {name: ğŸ‡¯ğŸ‡µ Japan, type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 300, tolerance: 20, filter: "(?=.*(æ—¥|JP|(?i)ğŸ‡¯ğŸ‡µ Japan))"}
  - {name: ğŸ‡°ğŸ‡· Korea, type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 300, tolerance: 20, filter: "(?=.*(éŸ©|KR|(?i)ğŸ‡°ğŸ‡· Korea))"}
  - {name: ğŸ‡ºğŸ‡² United States, type: url-test, include-all: true, url: "https://www.gstatic.com/generate_204", interval: 300, tolerance: 20, filter: "(?=.*(ç¾|US|(?i)States|America))"}

# è§„åˆ™åŒ¹é…
rules:
  - RULE-SET,private_domain,DIRECT
  - RULE-SET,ai_domain,ğŸ¤– AI
  - RULE-SET,github_domain,ğŸ‘¨â€ğŸ’» GitHub
  - RULE-SET,youtube_domain,ğŸ“¹ YouTube
  - RULE-SET,netflix_domain,ğŸ¥ Netflix
  - RULE-SET,spotify_domain,ğŸ¶ Spotify
  - RULE-SET,steam_domain,ğŸ® Game
  - RULE-SET,playstation_domain,ğŸ® Game
  - RULE-SET,nintendo_domain,ğŸ® Game
  - RULE-SET,xbox_domain,ğŸ® Game
  - RULE-SET,google_domain,ğŸ“¢ Google
  - RULE-SET,microsoft_domain,ğŸªŸ Microsoft
  - RULE-SET,apple_domain,ğŸ Apple
  - RULE-SET,gfw_domain,âœ… Static
  - RULE-SET,geolocation-!cn_domain,âœ… Static
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,netflix_ip,ğŸ¥ Netflix,no-resolve
  - RULE-SET,google_ip,ğŸ“¢ Google,no-resolve
  - RULE-SET,apple_ip,ğŸ Apple,no-resolve
  - RULE-SET,cn_ip,DIRECT
  - MATCH,ğŸŸ Final

# è§„åˆ™é›†
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  private_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/private.mrs"}
  ai_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/category-ai-!cn.mrs"}
  github_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/github.mrs"}
  youtube_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/youtube.mrs"}
  netflix_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/netflix.mrs"}
  spotify_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/spotify.mrs"}
  steam_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/steam.mrs"}
  playstation_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/playstation.mrs"}
  nintendo_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/nintendo.mrs"}
  xbox_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/xbox.mrs"}
  google_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/google.mrs"}
  microsoft_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/microsoft.mrs"}
  apple_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/apple.mrs"}
  gfw_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/gfw.mrs"}
  geolocation-!cn_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: {<<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/cn.mrs"}
  netflix_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/netflix.mrs"}
  google_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/google.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/apple.mrs"}
  cn_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/cn.mrs"}
